//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int PRODUCTID { get; set; }

        [Required(ErrorMessage = "Not Null Product Name ")]
        public string PRODUCTNAME { get; set; }
        [Required(ErrorMessage = "Not Null Brand")]
        public string BRAND { get; set; }
        [Required(ErrorMessage = "Not Null Price")]
        public Nullable<int> PRICE { get; set; }
        [Required(ErrorMessage = "Not Null Stock")]
        public Nullable<int> STOCK { get; set; }
        [Required(ErrorMessage = "Not Null Category ID ")]
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<bool> PRODUCTSTATUS { get; set; }
        [Required(ErrorMessage = "Not Null Product Image ")]
        public string PRODUCTIMAGE { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
