//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sales
    {
        public int SALESID { get; set; }
        [Required(ErrorMessage = "Not Null Product ID ")]
        public Nullable<int> PRODUCTID { get; set; }
        [Required(ErrorMessage = "Not Null Piece ")]
        public Nullable<int> PIECE { get; set; }
        [Required(ErrorMessage = "Not Null Price ")]
        public Nullable<int> PRICE { get; set; }
        [Required(ErrorMessage = "Not Null Customer ID")]
        public Nullable<int> CUSTOMERID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
