//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int WorkerID { get; set; }
        public string WorkerAccountName { get; set; }
        public string WorkerName { get; set; }
        public string WorkerSurname { get; set; }
        public string Password { get; set; }
    }
}
